sonar.projectKey=SQLutionsFATEC_API-6-Semestre-Frontend
sonar.organization=sqlutionsfatec-2

sonar.projectName=Analysis Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx

sonar.exclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx,src/test/**

sonar.coverage.exclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx,src/test/**,src/main.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8